apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/opa-gatekeeper
  catalog.kubestack.com/variant: base
  app.kubernetes.io/version: v3.4.0
commonLabels:
  app.kubernetes.io/component: admission-controller
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: opa-gatekeeper
resources:
- gatekeeper.yaml
